create table if not exists public._health (
  id bigint generated by default as identity primary key,
  checked_at timestamptz not null default now()
);

alter table public._health enable row level security;

create policy "Allow public health reads"
  on public._health
  for select
  to anon, authenticated
  using (true);
